In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#path of the Network Dataset
train_path = r"C:\Users\Milanjeet Singh\Desktop\New folder\archive (2)\nsl-kdd\KDDTrain+.txt"

In [3]:
#List of Features in out Dataset
Column_Name = ["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label","difficulty_level"]

In [4]:
#Making a pandas DataFrame
Df = pd.read_csv(train_path,names=Column_Name,header=None)
Df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label,difficulty_level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,...,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
2,0,tcp,private,S0,0,0,0,0,0,0,...,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune,19
3,0,tcp,http,SF,232,8153,0,0,0,0,...,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,...,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21

Data-Preprocessing

In [5]:
#Removing the Feature ['difficulty_level]
Df = Df.drop(['difficulty_level'],axis=1)

In [6]:
Df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [7]:
#Checking the types of Network Attacks available in the Dataset
Attacks = Df['label'].unique()
print(Attacks)

['normal' 'neptune' 'warezclient' 'ipsweep' 'portsweep' 'teardrop' 'nmap'
 'satan' 'smurf' 'pod' 'back' 'guess_passwd' 'ftp_write' 'multihop'
 'rootkit' 'buffer_overflow' 'imap' 'warezmaster' 'phf' 'land'
 'loadmodule' 'spy' 'perl']

In [8]:
Df['label'].value_counts()

normal             67343
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: label, dtype: int64

In [9]:
Df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,neptune
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [10]:
#types of Protocols being used
Df['protocol_type'].value_counts()

tcp     102689
udp      14993
icmp      8291
Name: protocol_type, dtype: int64

In [11]:
#Categoriziing these attacks into 4 main types of Network Attacks
def change_label(df):
  df.label.replace(['apache2','back','land','neptune','mailbomb','pod','processtable','smurf','teardrop','udpstorm','worm'],'Dos',inplace=True)
  df.label.replace(['ftp_write','guess_passwd','httptunnel','imap','multihop','named','phf','sendmail',
       'snmpgetattack','snmpguess','spy','warezclient','warezmaster','xlock','xsnoop'],'R2L',inplace=True)
  df.label.replace(['ipsweep','mscan','nmap','portsweep','saint','satan'],'Probe',inplace=True)
  df.label.replace(['buffer_overflow','loadmodule','perl','ps','rootkit','sqlattack','xterm'],'U2R',inplace=True)
  return df

In [12]:
Df = change_label(Df)
Df['label'].value_counts()

normal    67343
Dos       45927
Probe     11656
R2L         995
U2R          52
Name: label, dtype: int64

In [13]:
Df['service'].unique()

array(['ftp_data', 'other', 'private', 'http', 'remote_job', 'name',
       'netbios_ns', 'eco_i', 'mtp', 'telnet', 'finger', 'domain_u',
       'supdup', 'uucp_path', 'Z39_50', 'smtp', 'csnet_ns', 'uucp',
       'netbios_dgm', 'urp_i', 'auth', 'domain', 'ftp', 'bgp', 'ldap',
       'ecr_i', 'gopher', 'vmnet', 'systat', 'http_443', 'efs', 'whois',
       'imap4', 'iso_tsap', 'echo', 'klogin', 'link', 'sunrpc', 'login',
       'kshell', 'sql_net', 'time', 'hostnames', 'exec', 'ntp_u',
       'discard', 'nntp', 'courier', 'ctf', 'ssh', 'daytime', 'shell',
       'netstat', 'pop_3', 'nnsp', 'IRC', 'pop_2', 'printer', 'tim_i',
       'pm_dump', 'red_i', 'netbios_ssn', 'rje', 'X11', 'urh_i',
       'http_8001', 'aol', 'http_2784', 'tftp_u', 'harvest'], dtype=object)

Normalizing the Data

In [14]:
from sklearn.preprocessing import StandardScaler
Scaler = StandardScaler()

In [15]:
#A Function to normalize our Dataset
def normalization(df,col):
    for i in col:
        arr = df[i]
        arr = np.array(arr)
        df[i] = Scaler.fit_transform(arr.reshape(len(arr),1))
    return df

In [16]:
numeric_col = Df.select_dtypes(include='number').columns
Df = normalization(Df.copy(),numeric_col)

In [17]:
Df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,label
0,-0.110249,tcp,ftp_data,SF,-0.007679,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,...,-0.818890,-0.782367,-0.280282,0.069972,-0.289103,-0.639532,-0.624871,-0.224532,-0.376387,normal
1,-0.110249,udp,other,SF,-0.007737,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,...,-1.035688,-1.161030,2.736852,2.367737,-0.289103,-0.639532,-0.624871,-0.387635,-0.376387,normal
2,-0.110249,tcp,private,S0,-0.007762,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,...,-0.809857,-0.938287,-0.174417,-0.480197,-0.289103,1.608759,1.618955,-0.387635,-0.376387,Dos
3,-0.110249,tcp,http,SF,-0.007723,-0.002891,-0.014089,-0.089486,-0.007736,-0.095076,...,1.258754,1.066401,-0.439078,-0.383108,0.066252,-0.572083,-0.602433,-0.387635,-0.345084,normal
4,-0.110249,tcp,http,SF,-0.007728,-0.004814,-0.014089,-0.089486,-0.007736,-0.095076,...,1.258754,1.066401,-0.439078,-0.480197,-0.289103,-0.639532,-0.624871,-0.387635,-0.376387,normal

In [18]:
#using One-Hot encoder for these Features
cat_col = ['protocol_type','service','flag']
#Creating a Separate DataFrame for these Features
categorical = Df[cat_col]

In [19]:
#One Hot-Encoded Data
categorical = pd.get_dummies(categorical,columns=cat_col)
categorical.head()

,protocol_type_icmp,protocol_type_tcp,protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [20]:
Copy = Df

In [21]:
Copy = pd.concat([Copy,categorical],axis=1)
Copy.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,-0.110249,tcp,ftp_data,SF,-0.007679,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,...,0,0,0,0,0,0,0,0,1,0
1,-0.110249,udp,other,SF,-0.007737,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,...,0,0,0,0,0,0,0,0,1,0
2,-0.110249,tcp,private,S0,-0.007762,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,...,0,0,0,0,1,0,0,0,0,0
3,-0.110249,tcp,http,SF,-0.007723,-0.002891,-0.014089,-0.089486,-0.007736,-0.095076,...,0,0,0,0,0,0,0,0,1,0
4,-0.110249,tcp,http,SF,-0.007728,-0.004814,-0.014089,-0.089486,-0.007736,-0.095076,...,0,0,0,0,0,0,0,0,1,0

In [22]:
Copy = Copy.drop(['protocol_type','service','flag'],axis=1)

In [23]:
Copy.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,-0.110249,-0.007679,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,-0.809262,-0.011664,...,0,0,0,0,0,0,0,0,1,0
1,-0.110249,-0.007737,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,-0.809262,-0.011664,...,0,0,0,0,0,0,0,0,1,0
2,-0.110249,-0.007762,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,-0.809262,-0.011664,...,0,0,0,0,1,0,0,0,0,0
3,-0.110249,-0.007723,-0.002891,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,1.235694,-0.011664,...,0,0,0,0,0,0,0,0,1,0
4,-0.110249,-0.007728,-0.004814,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,1.235694,-0.011664,...,0,0,0,0,0,0,0,0,1,0

In [24]:
Copy['label'].unique()

array(['normal', 'Dos', 'R2L', 'Probe', 'U2R'], dtype=object)

In [25]:
#Converting the whole Dataset into Binary Classification Dataset
Copy['label'] = pd.DataFrame(Copy.label.map(lambda x:'normal' if x=='normal' else 'abnormal'))
Copy['label'].unique()

array(['normal', 'abnormal'], dtype=object)

In [26]:
Copy.head()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,-0.110249,-0.007679,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,-0.809262,-0.011664,...,0,0,0,0,0,0,0,0,1,0
1,-0.110249,-0.007737,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,-0.809262,-0.011664,...,0,0,0,0,0,0,0,0,1,0
2,-0.110249,-0.007762,-0.004919,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,-0.809262,-0.011664,...,0,0,0,0,1,0,0,0,0,0
3,-0.110249,-0.007723,-0.002891,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,1.235694,-0.011664,...,0,0,0,0,0,0,0,0,1,0
4,-0.110249,-0.007728,-0.004814,-0.014089,-0.089486,-0.007736,-0.095076,-0.027023,1.235694,-0.011664,...,0,0,0,0,0,0,0,0,1,0

In [27]:
Copy['label'] = pd.DataFrame(Copy.label.map(lambda x:0 if x=='normal' else 1))
Copy['label'].unique()

array([0, 1], dtype=int64)

In [28]:
Df_x = Copy.drop(['label'],axis=1)
Df_y = Copy['label']

In [29]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(Df_x,Df_y,test_size=0.25,random_state=42 )

In [30]:
from sklearn.linear_model import LogisticRegression
Model = LogisticRegression()

In [31]:
Model.fit(train_x, train_y)

c:\Anaconda\envs\tf-gpu\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [32]:
Predict = Model.predict(test_x)

In [33]:
from sklearn.metrics import accuracy_score
print("Accuracy :" ,accuracy_score(test_y,Predict)*100)

Accuracy : 97.14866323744205

In [34]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras import layers

In [35]:
Deep_Model = Sequential()

In [36]:
#First Layer of Neuron
Deep_Model.add(layers.Dense(122,input_dim=122))

In [37]:
#Second Layer
Deep_Model.add(layers.Dense(500,activation='relu'))

In [38]:
#Third Layer
Deep_Model.add(layers.Dense(500,activation='relu'))

In [39]:
#3rd Neural Layer
Deep_Model.add(layers.Dense(100,activation='relu'))

In [40]:
#Final layer
Deep_Model.add(layers.Dense(1,activation='sigmoid'))

In [41]:
Deep_Model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 122)               15006
_________________________________________________________________
dense_1 (Dense)              (None, 500)               61500
_________________________________________________________________
dense_2 (Dense)              (None, 500)               250500
_________________________________________________________________
dense_3 (Dense)              (None, 100)               50100
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 101
=================================================================
Total params: 377,207
Trainable params: 377,207
Non-trainable params: 0
_________________________________________________________________

In [42]:
_, val_x, _, val_y = train_test_split(train_x,train_y,test_size=0.25,random_state=42)

In [49]:
Deep_Model.compile(optimizer = tf.keras.optimizers.RMSprop(learning_rate= 2e-5) , loss='binary_crossentropy',metrics='accuracy')

In [50]:
Deep_Model.fit(train_x,train_y,epochs=10,validation_data=(val_x,val_y),validation_steps=10)

Epoch 1/10
2953/2953 [==============================] - 23s 7ms/step - loss: 0.0711 - accuracy: 0.9759 - val_loss: 0.0396 - val_accuracy: 0.9864
Epoch 2/10
2953/2953 [==============================] - 21s 7ms/step - loss: 0.0339 - accuracy: 0.9893 - val_loss: 0.0275 - val_accuracy: 0.9926
Epoch 3/10
2953/2953 [==============================] - 21s 7ms/step - loss: 0.0258 - accuracy: 0.9924 - val_loss: 0.0226 - val_accuracy: 0.9939
Epoch 4/10
2953/2953 [==============================] - 21s 7ms/step - loss: 0.0230 - accuracy: 0.9932 - val_loss: 0.0208 - val_accuracy: 0.9942
Epoch 5/10
2953/2953 [==============================] - 21s 7ms/step - loss: 0.0212 - accuracy: 0.9938 - val_loss: 0.0182 - val_accuracy: 0.9945
Epoch 6/10
2953/2953 [==============================] - 21s 7ms/step - loss: 0.0196 - accuracy: 0.9943 - val_loss: 0.0160 - val_accuracy: 0.9954
Epoch 7/10
2953/2953 [==============================] - 22s 7ms/step - loss: 0.0184 - accuracy: 0.9945 - val_loss: 0.0150 - val_accuracy: 0.9950
Epoch 8/10
2953/2953 [==============================] - 22s 7ms/step - loss: 0.0169 - accuracy: 0.9948 - val_loss: 0.0166 - val_accuracy: 0.9950
Epoch 9/10
2953/2953 [==============================] - 22s 7ms/step - loss: 0.0164 - accuracy: 0.9951 - val_loss: 0.0135 - val_accuracy: 0.9955
Epoch 10/10
2953/2953 [==============================] - 21s 7ms/step - loss: 0.0157 - accuracy: 0.9953 - val_loss: 0.0125 - val_accuracy: 0.9964

In [51]:
Predict = Deep_Model.predict(test_x)

In [53]:
Predict = np.round(Predict)

In [54]:
print("Accuracy of Deep Model: ",accuracy_score(test_y,Predict)*100)

Accuracy of Deep Model:  99.49831713977265